"use client";

import { useState } from "react";

export type Enrolment = { qr: string; secret: string };

/** QR code to scan with an authenticator app, plus the key for typing in by hand. */
export default function MfaEnrolment({ enrolment, intro }: { enrolment: Enrolment; intro: string }) {
  const [showKey, setShowKey] = useState(false);
  const grouped = enrolment.secret.replace(/(.{4})/g, "$1 ").trim();
  return (
    <div className="space-y-3">
      <p className="text-[14px] leading-[22px]">{intro}</p>
      <ol className="list-decimal space-y-1 pl-5 text-[14px] leading-[22px] text-muted">
        <li>Open Google Authenticator or Microsoft Authenticator on your phone.</li>
        <li>Add an account and scan this QR code.</li>
        <li>Enter the 6-digit code the app shows for RNK Legalheads CMS.</li>
      </ol>
      {/* eslint-disable-next-line @next/next/no-img-element -- data URL generated by our backend */}
      <img src={enrolment.qr} alt="QR code for adding RNK Legalheads CMS to an authenticator app" width={180} height={180} className="border border-line bg-white p-2" />
      {showKey ? (
        <p className="text-[13px] leading-5">
          Key for typing in by hand: <code className="break-all bg-warm px-1.5 py-0.5 font-mono text-[13px]">{grouped}</code>
        </p>
      ) : (
        <button type="button" onClick={() => setShowKey(true)} className="inline-flex min-h-11 items-center text-[13px] underline underline-offset-4 md:min-h-0">
          Can&apos;t scan? Show the key to type in
        </button>
      )}
    </div>
  );
}
